### ISSUE TITLE
Panic when json is invalid

### ISSUE THREAD

**Issue by xhit** [tamerh/jsparser#1]
If json is invalid then this error is triggered

```
goroutine 7 [running]:
        C:/Users/sdelacruz/Documents/go/src/github.com/tamerh/jsparser/jsparser.go:153 +0x29d
created by github.com/tamerh/jsparser.(*JsonParser).Stream
        C:/Users/sdelacruz/Documents/go/src/github.com/tamerh/jsparser/jsparser.go:70 +0x46
```

**Comment by xhit** [comment]
Pull request #2 fix this issue.

**Comment by tamerh** [comment]
Now validations added for start and end of values it should be fixed now.
